services:
  papermc:
    image: itzg/minecraft-server
    container_name: testi-papermc-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.4"
      MEMORY: "4G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "minecraft"
      RCON_PORT: "25575"
    ports:
      - "25565:25565"  # Minecraft Server
    volumes:
      - ./data:/data
      - ../build/libs:/libs
    entrypoint: >
      /bin/sh -c "
      mkdir -p /data/plugins && \
      echo 'Cleaning up old plugins...' && \
      rm -f /data/plugins/*.jar && \
      echo 'Copying new plugins...' && \
      cp -v /libs/*.jar /data/plugins/ && \
      exec /start"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: testi-postgres
    environment:
      POSTGRES_DB: "minigames"
      POSTGRES_USER: "minecraft"
      POSTGRES_PASSWORD: "pw"
    ports:
      - "5432:5432"
    volumes:
      - testi_postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  testi_postgres_data: